# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["ntfs"];

  #  fileSystems."/" =
  #    {
  #      device = "/dev/disk/by-uuid/b8f656f5-8503-4f46-9239-828c14faac01";
  #      fsType = "ext4";
  #    };
  #
  #  fileSystems."/boot" =
  #    {
  #      device = "/dev/disk/by-uuid/B80C-DCC7";
  #      fsType = "vfat";
  #    };

  #  swapDevices =
  #    [{ device = "/dev/disk/by-uuid/3a47ecca-94e7-4af6-a1e1-875f7e882845"; }];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/03f81600-2980-485c-8c86-68624c9ddaac";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/38B1-E99B";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  #  fileSystems."/mnt/ssd" =
  #    {
  #      device = "/dev/nvme0n1p3";
  #      fsType = "ntfs-3g";
  #      options = [ "rw" "michaell" ];
  #    };
  #  fileSystems."/mnt/hdd" =
  #    {
  #      device = "/dev/sda2";
  #      fsType = "ntfs-3g";
  #      options = [ "rw" "michaell" ];
  #    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
